syntax = "proto3";

package Engine.Networking.Proto;

// A generic wrapper for property values (Int, Float, String, Vector3, etc.)
message PropertyData {
    oneof value {
        int32 int_value = 1;
        float float_value = 2;
        string string_value = 3;
        bool bool_value = 4;
        Vector3 vector3_value = 5;
    }
}

message Vector3 {
    float x = 1;
    float y = 2;
    float z = 3;
}

// Represents a change in a specific instance's properties
message ReplicationUpdate {
    uint64 instance_id = 1;
    string class_name = 2; // Usually only needed if creating the instance
    map<string, PropertyData> properties = 3;
}

message ReplicationPacket {
    repeated ReplicationUpdate updates = 1;
}

message RemoteEventPacket {
    uint64 instance_id = 1; // Instance ID of the RemoteEvent
    repeated PropertyData args = 2;
}

message PlayerInputPacket {
    uint32 sequence_number = 1;
    float delta_time = 2;
    Vector3 move_direction = 3;
    bool jump_requested = 4;
}

message PlayerStateSnapshotPacket {
    uint32 sequence_number = 1; // Acked sequence number
    Vector3 position = 2;
    Vector3 velocity = 3;
}

// Master packet that can hold either replication data, remote events, or prediction packets
message NetworkPacket {
    oneof payload {
        ReplicationPacket replication = 1;
        RemoteEventPacket remote_event = 2;
        PlayerInputPacket player_input = 3;
        PlayerStateSnapshotPacket player_snapshot = 4;
    }
}
