#include "MeshAssetExporter.h"
#include <fstream>
#include <iomanip>

namespace Engine::Asset {

bool MeshAssetExporter::exportToObj(const Geometry::EditableMesh& mesh, const std::string& absoluteFilePath) {
    std::ofstream out(absoluteFilePath);
    if (!out.is_open()) return false;

    out << "# Nexus Studio Exported Mesh\n";
    out << "# Generated by In-Engine 3D Modeling Suite\n\n";

    const auto& vertices = mesh.getVertices();
    const auto& faces = mesh.getFaces();

    // Vertices (v)
    for (const auto& v : vertices) {
        if (!v.deleted) {
            out << "v " << std::fixed << std::setprecision(6)
                << v.position.x << " " << v.position.y << " " << v.position.z << "\n";
        }
    }

    // Texture coords (vt)
    for (const auto& v : vertices) {
        if (!v.deleted) {
            out << "vt " << std::fixed << std::setprecision(6)
                << v.u << " " << v.v << "\n";
        }
    }

    // Vertex normals (vn)
    for (const auto& v : vertices) {
        if (!v.deleted) {
            out << "vn " << std::fixed << std::setprecision(6)
                << v.normal.x << " " << v.normal.y << " " << v.normal.z << "\n";
        }
    }

    out << "\ns 1\n";

    // Map internal 0-indexed active vertices to 1-indexed OBJ vertices
    std::vector<int> vertRemap(vertices.size(), -1);
    int validCount = 1;
    for (size_t i = 0; i < vertices.size(); ++i) {
        if (!vertices[i].deleted) {
            vertRemap[i] = validCount++;
        }
    }

    // Faces (f v/vt/vn)
    for (const auto& f : faces) {
        if (f.deleted || f.vertices.size() < 3) continue;
        out << "f";
        for (uint32_t vIdx : f.vertices) {
            if (vIdx < vertRemap.size() && vertRemap[vIdx] > 0) {
                int objIdx = vertRemap[vIdx];
                out << " " << objIdx << "/" << objIdx << "/" << objIdx;
            }
        }
        out << "\n";
    }

    out.close();
    return true;
}

} // namespace Engine::Asset
